import { Project, Site, SiteFeatureCollection, AnalyticsOverview, Activity } from '../types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 1,
    name: 'Sundarbans Blue Carbon & Mangrove Bio-Shield',
    slug: 'sundarbans-blue-carbon-mangrove',
    description:
      'Restoration and high-resolution MRV monitoring of 4,200 hectares of degraded coastal mangrove estuaries in the Bay of Bengal, sequestering high-density tidal carbon while shielding coastal communities.',
    project_type: 'Mangrove Restoration',
    standard: 'Verra VCS',
    status: 'Active',
    country: 'India',
    region: 'West Bengal / Sundarbans Biosphere',
    biome: 'Mangrove / Coastal Wetland',
    estimated_annual_tco2e: 48500,
    target_biodiversity_score: 92,
    budget: 2400000,
    developer_name: 'Darukaa BlueCarbon Alliance',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    total_sites: 2,
    total_hectares: 3840,
    total_carbon_stock: 948000,
    avg_canopy_cover: 80.25,
  },
  {
    id: 2,
    name: 'Amazonian Alto Mayo Primary Rainforest Corridor',
    slug: 'amazonian-alto-mayo-corridor',
    description:
      'Community-led indigenous REDD+ and canopy enrichment initiative protecting critical watershed headwaters in the San Martin cloud forest and primary lowland Amazon.',
    project_type: 'Avoided Deforestation (REDD+)',
    standard: 'Plan Vivo',
    status: 'Verified',
    country: 'Peru',
    region: 'San Martín / Rioja',
    biome: 'Tropical Rainforest',
    estimated_annual_tco2e: 92000,
    target_biodiversity_score: 96.5,
    budget: 4100000,
    developer_name: 'Alto Mayo Conservation Trust',
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    total_sites: 2,
    total_hectares: 6850,
    total_carbon_stock: 2110000,
    avg_canopy_cover: 92.5,
  },
  {
    id: 3,
    name: 'Cairngorms Peatland Rewetting & Caledonian Forest',
    slug: 'cairngorms-peatland-caledonian',
    description:
      'Highland landscape-scale hydrological restoration blocking erosion gullies across ombrotrophic blanket bogs, revitalizing native Scots pine regeneration.',
    project_type: 'Peatland Rewetting',
    standard: 'Gold Standard',
    status: 'Active',
    country: 'United Kingdom',
    region: 'Scottish Highlands',
    biome: 'Boreal Peatland & Taiga',
    estimated_annual_tco2e: 31500,
    target_biodiversity_score: 88,
    budget: 1850000,
    developer_name: 'Cairngorms Wildlands Foundation',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    total_sites: 2,
    total_hectares: 2950,
    total_carbon_stock: 535000,
    avg_canopy_cover: 62.5,
  },
  {
    id: 4,
    name: 'Serengeti-Mara Acacia Savanna Wildlife Corridor',
    slug: 'serengeti-mara-savanna-corridor',
    description:
      'Community pastoralist rotational grazing management and savanna soil carbon enhancement securing historic mammal migration corridors along the Kenyan border.',
    project_type: 'Grassland & Savanna Restoration',
    standard: 'Verra VCS',
    status: 'Under Validation',
    country: 'Tanzania',
    region: 'Mara Region',
    biome: 'Tropical Savanna & Grassland',
    estimated_annual_tco2e: 28000,
    target_biodiversity_score: 94.5,
    budget: 1600000,
    developer_name: 'Mara Conservancy Trust',
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    total_sites: 1,
    total_hectares: 5200,
    total_carbon_stock: 442000,
    avg_canopy_cover: 42.0,
  },
  {
    id: 5,
    name: 'Borneo Katingan Peat Swamp Forest Sanctuary',
    slug: 'borneo-katingan-peat-swamp',
    description:
      'Ecosystem restoration concession conserving deep peat domes containing up to 14 meters of organic soil, protecting endangered Bornean orangutans and proboscis monkeys.',
    project_type: 'Avoided Peatland Conversion',
    standard: 'Verra VCS',
    status: 'Verified',
    country: 'Indonesia',
    region: 'Central Kalimantan',
    biome: 'Tropical Peat Swamp',
    estimated_annual_tco2e: 115000,
    target_biodiversity_score: 98,
    budget: 5200000,
    developer_name: 'PT Rimba Makmur Utama',
    created_at: new Date(Date.now() - 150 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    total_sites: 2,
    total_hectares: 12400,
    total_carbon_stock: 4712000,
    avg_canopy_cover: 89.0,
  },
];

export const MOCK_SITES: Site[] = [
  {
    id: 1,
    project_id: 1,
    name: 'Gosaba Tidal Restoration Parcel',
    code: 'SND-GSB-01',
    area_hectares: 2150,
    habitat_type: 'Dense Rhizophora Mangrove',
    elevation_m: 4.5,
    centroid_lat: 22.127,
    centroid_lng: 88.813,
    carbon_density_tco2e_per_ha: 260,
    canopy_cover_pct: 86.5,
    species_richness: 178,
    soil_organic_carbon_pct: 6.8,
    threat_level: 'Moderate',
    monitoring_status: 'Active Satellite Scan',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [88.785, 22.145],
          [88.835, 22.148],
          [88.842, 22.112],
          [88.791, 22.105],
          [88.785, 22.145],
        ],
      ],
    },
  },
  {
    id: 2,
    project_id: 1,
    name: 'Matla Estuary Mudflat Buffer',
    code: 'SND-MTL-02',
    area_hectares: 1690,
    habitat_type: 'Avicennia Pioneer Mudflat',
    elevation_m: 2.8,
    centroid_lat: 22.041,
    centroid_lng: 88.694,
    carbon_density_tco2e_per_ha: 210,
    canopy_cover_pct: 74.0,
    species_richness: 142,
    soil_organic_carbon_pct: 5.4,
    threat_level: 'Low',
    monitoring_status: 'Active Satellite Scan',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [88.665, 22.055],
          [88.712, 22.062],
          [88.725, 22.028],
          [88.675, 22.019],
          [88.665, 22.055],
        ],
      ],
    },
  },
  {
    id: 3,
    project_id: 2,
    name: 'Naranjos Ridge Primary Canopy',
    code: 'AMZ-NRJ-01',
    area_hectares: 4200,
    habitat_type: 'Montane Cloud Rainforest',
    elevation_m: 1150,
    centroid_lat: -5.75,
    centroid_lng: -77.346,
    carbon_density_tco2e_per_ha: 310,
    canopy_cover_pct: 94.0,
    species_richness: 340,
    soil_organic_carbon_pct: 7.2,
    threat_level: 'Moderate',
    monitoring_status: 'Verified',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-77.385, -5.725],
          [-77.315, -5.718],
          [-77.308, -5.775],
          [-77.378, -5.782],
          [-77.385, -5.725],
        ],
      ],
    },
  },
];

export const MOCK_SITES_GEOJSON: SiteFeatureCollection = {
  type: 'FeatureCollection',
  features: MOCK_SITES.map((s) => ({
    type: 'Feature',
    id: s.id,
    geometry: s.geometry,
    properties: {
      id: s.id,
      project_id: s.project_id,
      name: s.name,
      code: s.code,
      area_hectares: s.area_hectares,
      habitat_type: s.habitat_type,
      elevation_m: s.elevation_m,
      centroid_lat: s.centroid_lat,
      centroid_lng: s.centroid_lng,
      carbon_density_tco2e_per_ha: s.carbon_density_tco2e_per_ha,
      canopy_cover_pct: s.canopy_cover_pct,
      species_richness: s.species_richness,
      soil_organic_carbon_pct: s.soil_organic_carbon_pct,
      threat_level: s.threat_level,
      monitoring_status: s.monitoring_status,
      total_carbon_stock: Math.round(s.area_hectares * s.carbon_density_tco2e_per_ha),
    },
  })),
};

export const MOCK_OVERVIEW: AnalyticsOverview = {
  total_projects: 5,
  total_sites: 9,
  total_hectares: 31240,
  total_carbon_tco2e: 8747000,
  avg_biodiversity_score: 93.8,
  avg_canopy_cover: 78.4,
  active_verifications: 3,
  carbon_credits_value_usd: 161819500,
  monthly_carbon_trends: [
    {
      month_label: 'Oct 2025',
      actual_tco2e: 680000,
      baseline_tco2e: 520000,
      target_tco2e: 670000,
      flux_tco2e: 24500,
    },
    {
      month_label: 'Nov 2025',
      actual_tco2e: 705000,
      baseline_tco2e: 522000,
      target_tco2e: 695000,
      flux_tco2e: 25000,
    },
    {
      month_label: 'Dec 2025',
      actual_tco2e: 731000,
      baseline_tco2e: 524000,
      target_tco2e: 720000,
      flux_tco2e: 26000,
    },
    {
      month_label: 'Jan 2026',
      actual_tco2e: 758000,
      baseline_tco2e: 525000,
      target_tco2e: 745000,
      flux_tco2e: 27000,
    },
    {
      month_label: 'Feb 2026',
      actual_tco2e: 786000,
      baseline_tco2e: 527000,
      target_tco2e: 770000,
      flux_tco2e: 28000,
    },
    {
      month_label: 'Mar 2026',
      actual_tco2e: 815000,
      baseline_tco2e: 528000,
      target_tco2e: 795000,
      flux_tco2e: 29000,
    },
  ],
  biodiversity_radar: {
    taxa: [
      'Avian Fauna',
      'Mammalia',
      'Canopy Flora',
      'Lepidoptera',
      'Soil Microbiome',
      'Amphibians',
    ],
    current_index: [94, 88, 96, 91, 85, 92],
    baseline_index: [72, 65, 78, 70, 68, 64],
  },
  biome_breakdown: [
    { biome: 'Tropical Peat Swamp', project_count: 1, hectares: 12400, tco2e: 4712000 },
    { biome: 'Tropical Rainforest', project_count: 1, hectares: 6850, tco2e: 2110000 },
    { biome: 'Tropical Savanna', project_count: 1, hectares: 5200, tco2e: 442000 },
    { biome: 'Mangrove / Wetland', project_count: 1, hectares: 3840, tco2e: 948000 },
    { biome: 'Boreal Peatland', project_count: 1, hectares: 2950, tco2e: 535000 },
  ],
};

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 1,
    action_type: 'TELEMETRY_SCAN',
    title: 'On-Demand Satellite Scan: SND-GSB-01',
    description:
      'Sentinel-2 multispectral reflectance calibrated for Gosaba Tidal Restoration. Measured NDVI: 0.84, Canopy: 86.5%.',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 2,
    action_type: 'VERIFICATION',
    title: 'Verra VCS Baseline Sealed: AMZ-NRJ-01',
    description: 'Third-party auditor verified 92,000 tCO2e annual net sequestration curve.',
    timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    id: 3,
    action_type: 'POLYGON_DRAWN',
    title: 'New Spatial Parcel Delineated: CG-KNG-01',
    description:
      'Cairngorms peatland parcel (1,450 ha) geometry validated via Shapely geodesic projection.',
    timestamp: new Date(Date.now() - 360 * 60000).toISOString(),
  },
];
